version: '3.7'

networks:
  internal:

services:
  kinbaku:
    build: kinbaku
    restart: unless-stopped
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=$KINBAKU_SECRET_KEY_BASE
      - KINBAKU_DOMAIN=$KINBAKU_DOMAIN
      - KINBAKU_SMTP_ADDRESS=$KINBAKU_SMTP_ADDRESS
      - KINBAKU_SMTP_DOMAIN=$KINBAKU_SMTP_DOMAIN
      - KINBAKU_SMTP_USER_NAME=$KINBAKU_SMTP_USER_NAME
      - KINBAKU_SMTP_PASSWORD=$KINBAKU_SMTP_PASSWORD
      - KINBAKU_SMTP_PORT=$KINBAKU_SMTP_PORT
    volumes:
      - ./production.sqlite3:/opt/app/db/production.sqlite3
      - ./storage/production:/opt/app/storage
    networks:
      - internal

  kinbaku-dev:
    build: kinbaku-dev
    environment:
      - RAILS_ENV=development
      - KINBAKU_DOMAIN=$KINBAKU_DEV_DOMAIN
      - KINBAKU_SMTP_ADDRESS=$KINBAKU_DEV_SMTP_ADDRESS
      - KINBAKU_SMTP_DOMAIN=$KINBAKU_DEV_SMTP_DOMAIN
      - KINBAKU_SMTP_USER_NAME=$KINBAKU_DEV_SMTP_USER_NAME
      - KINBAKU_SMTP_PASSWORD=$KINBAKU_DEV_SMTP_PASSWORD
      - KINBAKU_SMTP_PORT=$KINBAKU_DEV_SMTP_PORT

    volumes:
      - ./development.sqlite3:/opt/app/db/development.sqlite3
      - ./storage/development:/opt/app/storage
    networks:
      - internal

  www:
    image: caddy:2
    restart: unless-stopped
    environment:
      - KINBAKU_DOMAIN
      - KINBAKU_DEV_DOMAIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:


