version: '3.7'

networks:
  internal:

services:
  kinbaku:
    build: kinbaku
    restart: unless-stopped
    environment:
      - RAILS_ENV=development  # TODO fix for production
    volumes:
      - ./production.sqlite3:/opt/app/db/development.sqlite3  # TODO fix for production
      - ./storage/production:/opt/app/storage
    networks:
      - internal

  kinbaku-dev:
    build: kinbaku-dev
    environment:
      - RAILS_ENV=development
    volumes:
      - ./development.sqlite3:/opt/app/db/development.sqlite3
      - ./storage/development:/opt/app/storage
    networks:
      - internal

  www:
    image: caddy:2
    restart: unless-stopped
    environment:
      - KINBAKU_DOMAIN
      - KINBAKU_DEV_DOMAIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:


